// postbuild: emit dist/cli.cjs, a thin CJS launcher that re-execs the ESM
// bundle. npm bin shims resolve a .cjs entry most reliably across setups.
import { writeFile, chmod } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const dist = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "dist");
const file = path.join(dist, "cli.cjs");

await writeFile(
  file,
  '#!/usr/bin/env node\n// Generated by scripts/cli-entry.mjs. Re-execs the ESM bundle.\nimport("./index.js");\n',
  "utf8",
);
await chmod(file, 0o755);
console.log("wrote", file);
